services:
  news-minio:
    image: minio/minio
    command: server --console-address ":9001" /var/lib/minio/data
    ports:
      - "5002:9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      timeout: 10s
      interval: 10s
      retries: 5
    volumes:
      - news-minio-data:/var/lib/minio/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
  
  news-db:
    image: postgres
    ports:
      - "5001:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - news-db-data:/var/lib/postgresql/data
  
  news:
    build: ./
    depends_on:
      news-minio:
        condition: service_healthy
      news-db:
        condition: service_healthy
    ports:
      - "5000:5000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/healthy" ]
      timeout: 10s
      interval: 10s
      retries: 5
    volumes:
      - './:/app:z'
      - '/app/bin'
      - '/app/obj'

volumes:
  news-minio-data:
  news-db-data: