// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Newleaf.Data;
using Newleaf.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Newleaf.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ChannelCode", new[] { "email", "none", "telegram" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "Frequency", new[] { "custom", "every_day", "every_month", "every_quarter", "every_week", "every_year", "once" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "StatusCode", new[] { "lost", "sent" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Newleaf.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BlobId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NewsletterId")
                        .HasColumnType("integer");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NewsletterId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Newleaf.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<ChannelCode>("Channel")
                        .HasColumnType("\"ChannelCode\"");

                    b.Property<int>("NewsletterId")
                        .HasColumnType("integer");

                    b.Property<StatusCode>("Status")
                        .HasColumnType("\"StatusCode\"");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NewsletterId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Newleaf.Models.Newsletter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Newsletters");
                });

            modelBuilder.Entity("Newleaf.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DelayedTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Frequency>("Frequency")
                        .HasColumnType("\"Frequency\"");

                    b.Property<TimeSpan?>("FrequencySpan")
                        .HasColumnType("interval");

                    b.PrimitiveCollection<int[]>("StudentIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("Newleaf.Models.Attachment", b =>
                {
                    b.HasOne("Newleaf.Models.Newsletter", null)
                        .WithMany("Attachments")
                        .HasForeignKey("NewsletterId");

                    b.HasOne("Newleaf.Models.Template", null)
                        .WithMany("Attachments")
                        .HasForeignKey("TemplateId");
                });

            modelBuilder.Entity("Newleaf.Models.Message", b =>
                {
                    b.HasOne("Newleaf.Models.Newsletter", "Newsletter")
                        .WithMany("Messages")
                        .HasForeignKey("NewsletterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Newsletter");
                });

            modelBuilder.Entity("Newleaf.Models.Newsletter", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Newleaf.Models.Template", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
